[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
holonic_futarchy = "C1Hdqy8NDbNWHTM8Mhy67pTzTsZbGtwKGpz33vrzReuK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/solanadev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
